const state={data:[],meta:null,date:new Date(),filter:'ALL',query:'',range:7};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const today=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())};
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const money=v=>v==null?'待公告':`$${Number(v).toLocaleString('zh-TW',{maximumFractionDigits:6})}`;
const typeName=t=>({ETF:'ETF',REIT:'REIT',ETN:'ETN',STOCK:'個股'})[t]||t;
const marketName=m=>m==='TWSE'?'上市':'上櫃';
const eventName=e=>({'ex-dividend':'除息','ex-rights':'除權','ex-rights-dividend':'除權息'})[e]||e;
function filtered(){const q=state.query.toLowerCase();return state.data.filter(x=>(state.filter==='ALL'||x.type===state.filter)&&(!q||x.symbol.toLowerCase().includes(q)||x.name.toLowerCase().includes(q)))}
async function loadData(showToast=false){try{const res=await fetch(`data/dividends.json?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const payload=await res.json();state.data=Array.isArray(payload)?payload:payload.items||[];state.meta=Array.isArray(payload)?null:payload;if(!state._initialized){const now=today();state.date=new Date(now.getFullYear(),now.getMonth(),1);state._initialized=true}updateStatus();render();if(showToast)toast('資料已重新載入')}catch(err){console.error(err);$('#calendar').innerHTML='<p class="empty">無法載入資料。請使用「啟動股息月曆.bat」開啟。</p>';$('#updateTime').textContent='資料載入失敗';toast('資料載入失敗')}}
function updateStatus(){if(!state.meta?.updatedAt){$('#updateTime').textContent='資料更新時間未提供';return}const d=new Date(state.meta.updatedAt);$('#updateTime').textContent=`資料更新：${d.toLocaleString('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}`}
function render(){renderCalendar();renderUpcoming()}
function renderCalendar(){const y=state.date.getFullYear(),m=state.date.getMonth(),items=filtered(),first=new Date(y,m,1),start=new Date(y,m,1-((first.getDay()+6)%7)),now=iso(today());$('#monthTitle').textContent=`${y} 年 ${m+1} 月`;const monthItems=items.filter(x=>x.exDividendDate.startsWith(`${y}-${String(m+1).padStart(2,'0')}`));$('#monthSummary').textContent=`本月 ${monthItems.length} 筆已公告除權息資訊`;
 let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const dateKey=iso(d),events=items.filter(x=>x.exDividendDate===dateKey),outside=d.getMonth()!==m;html+=`<div class="day${outside?' outside':''}${dateKey===now?' today':''}" data-date="${dateKey}"><div class="day-number"><span>${d.getDate()}</span>${events.length?`<span>${events.length} 檔</span>`:''}</div>${events.slice(0,3).map(eventHtml).join('')}${events.length>3?`<button class="more-button" data-more="${dateKey}" type="button">＋ ${events.length-3} 檔</button>`:''}</div>`}$('#calendar').innerHTML=html;bindEventButtons()}
function eventHtml(x){return `<button class="event ${x.type==='STOCK'?'stock':''}" data-key="${key(x)}" type="button"><span class="event-symbol">${esc(x.symbol)}</span><span class="event-name">${esc(x.name)}</span><span class="event-value ${x.status==='pending'?'pending':''}">${x.eventType==='ex-rights'?'除權':money(x.cashDividend)}</span></button>`}
function key(x){return encodeURIComponent([x.source,x.symbol,x.exDividendDate,x.eventType].join('|'))}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function bindEventButtons(){$$('[data-key]').forEach(b=>b.onclick=()=>showDetail(b.dataset.key));$$('[data-more]').forEach(b=>b.onclick=()=>showDay(b.dataset.more))}
function showDetail(encoded){const needle=decodeURIComponent(encoded),x=state.data.find(v=>[v.source,v.symbol,v.exDividendDate,v.eventType].join('|')===needle);if(!x)return;$('#detailContent').innerHTML=`<h2 class="detail-title">${esc(x.symbol)}</h2><p class="detail-name">${esc(x.name)}</p><dl class="detail-grid"><dt>類型</dt><dd>${typeName(x.type)}</dd><dt>市場</dt><dd>${marketName(x.market)}</dd><dt>事件</dt><dd>${eventName(x.eventType)}</dd><dt>除權息日</dt><dd>${x.exDividendDate.replaceAll('-','/')}</dd><dt>現金股利</dt><dd>${x.eventType==='ex-rights'?'—':`${money(x.cashDividend)}${x.cashDividend!=null?' / 股':''}`}</dd><dt>股票股利率</dt><dd>${x.stockDividendRatio==null?'—':x.stockDividendRatio}</dd><dt>狀態</dt><dd>${x.status==='pending'?'待公告':'已公告'}</dd><dt>資料來源</dt><dd>${x.source}</dd></dl>`;$('#detailDialog').showModal()}
function showDay(date){const list=filtered().filter(x=>x.exDividendDate===date);$('#dayContent').innerHTML=`<h2 class="detail-title">${date.replaceAll('-','/')}</h2><p class="detail-name">共 ${list.length} 檔除權息資訊</p><div class="day-list">${list.map(eventHtml).join('')}</div>`;$('#dayDialog').showModal();$('#dayContent').querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{$('#dayDialog').close();showDetail(b.dataset.key)})}
function renderUpcoming(){const start=today(),end=new Date(start);end.setDate(end.getDate()+state.range);const rows=filtered().filter(x=>{const d=new Date(`${x.exDividendDate}T00:00:00`);return d>=start&&d<=end&&x.eventType!=='ex-rights'}).sort((a,b)=>a.exDividendDate.localeCompare(b.exDividendDate)||a.symbol.localeCompare(b.symbol));$('#upcomingList').innerHTML=rows.length?rows.map(x=>`<div class="upcoming-row" tabindex="0" role="button" data-key="${key(x)}"><span class="date-chip">${x.exDividendDate.slice(5).replace('-','/')}</span><span class="security-code">${esc(x.symbol)}</span><span class="security-name">${esc(x.name)}</span><span class="amount">${money(x.cashDividend)}</span><span class="badge ${x.type==='STOCK'?'stock':''}">${typeName(x.type)}</span></div>`).join(''):`<p class="empty">未來 ${state.range} 天沒有符合條件的已公告除息資料。</p>`;$('#upcomingList').querySelectorAll('[data-key]').forEach(r=>{r.onclick=()=>showDetail(r.dataset.key);r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();r.click()}}})}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));state.filter=b.dataset.filter;render()});
$$('[data-range]').forEach(b=>b.onclick=()=>{$$('[data-range]').forEach(x=>x.classList.toggle('active',x===b));state.range=Number(b.dataset.range);renderUpcoming()});
$('#searchInput').oninput=e=>{state.query=e.target.value.trim();render()};
$('#prevMonth').onclick=()=>{state.date=new Date(state.date.getFullYear(),state.date.getMonth()-1,1);renderCalendar()};
$('#nextMonth').onclick=()=>{state.date=new Date(state.date.getFullYear(),state.date.getMonth()+1,1);renderCalendar()};
$('#todayBtn').onclick=()=>{const d=today();state.date=new Date(d.getFullYear(),d.getMonth(),1);renderCalendar()};
$('#reloadBtn').onclick=()=>loadData(true);$('#closeDialog').onclick=()=>$('#detailDialog').close();$('#closeDayDialog').onclick=()=>$('#dayDialog').close();
[$('#detailDialog'),$('#dayDialog')].forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
loadData();
